import {
	bigint,
	boolean,
	index,
	int,
	json,
	mysqlTable,
	text,
	timestamp,
	varchar,
} from "drizzle-orm/mysql-core";
import { user } from "./mysql-auth";

/**
 * MySQL schema.
 *
 * `./mysql-auth.ts` is generated by better-auth's schema generator.
 *
 * The application tables below are the health data cache. They exist in all
 * three dialect modules under the same table and column *names*; only the types
 * differ. They move as a set — editing one alone is what produces an app that
 * works on SQLite and falls over on Postgres. `./sqlite.ts` carries the
 * commentary explaining each decision.
 *
 * Four MySQL-specific details matter here, and three of them are the same traps
 * `scripts/normalize-auth-schema.ts` already strips out of generated output:
 *
 * - Identifiers are `varchar`, and `user_id` is `varchar(36)` because it has to
 *   match `user.id` exactly — a width mismatch is an errno 3780 foreign key
 *   failure at migration time.
 * - `json()` takes neither `{ mode: "json" }` nor a DEFAULT. Both JSON columns
 *   are `.notNull()` and always supplied by the writer.
 * - Every column in an index must be `varchar`, never `text`; MySQL needs a
 *   prefix length otherwise. That is why `data_type`, `grain` and friends are
 *   bounded while `resource_name` and `failure_message` stay `text`.
 * - Timestamps carry `fsp: 3` so millisecond precision survives.
 */
export * from "./mysql-auth";

/** Cached Google Health data points. See `./sqlite.ts` for the rationale. */
export const healthDataPoint = mysqlTable(
	"health_data_point",
	{
		id: varchar("id", { length: 32 }).primaryKey(),
		userId: varchar("user_id", { length: 36 })
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
		dataType: varchar("data_type", { length: 64 }).notNull(),
		grain: varchar("grain", { length: 16 }).default("point").notNull(),
		timeShape: varchar("time_shape", { length: 16 }).notNull(),
		observedAtMs: bigint("observed_at_ms", { mode: "number" }).notNull(),
		observedEndMs: bigint("observed_end_ms", { mode: "number" }).notNull(),
		observedTime: json("observed_time")
			.$type<Record<string, unknown>>()
			.notNull(),
		value: json("value").$type<Record<string, unknown>>().notNull(),
		source: json("source").$type<Record<string, unknown>>(),
		sourceKey: varchar("source_key", { length: 32 }),
		resourceName: text("resource_name"),
		contentHash: varchar("content_hash", { length: 32 }).notNull(),
		syncedAt: timestamp("synced_at", { fsp: 3 }).notNull(),
		createdAt: timestamp("created_at", { fsp: 3 }).defaultNow().notNull(),
	},
	(table) => [
		index("healthDataPoint_userId_dataType_observedAtMs_idx").on(
			table.userId,
			table.dataType,
			table.observedAtMs,
		),
	],
);

/** Per (user, data type) sync watermarks and failure state. */
export const healthSyncState = mysqlTable(
	"health_sync_state",
	{
		id: varchar("id", { length: 32 }).primaryKey(),
		userId: varchar("user_id", { length: 36 })
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
		dataType: varchar("data_type", { length: 64 }).notNull(),
		coveredFromMs: bigint("covered_from_ms", { mode: "number" }),
		coveredThroughMs: bigint("covered_through_ms", { mode: "number" }),
		backfillComplete: boolean("backfill_complete").default(false).notNull(),
		lastSyncAt: timestamp("last_sync_at", { fsp: 3 }),
		lastAttemptAt: timestamp("last_attempt_at", { fsp: 3 }),
		lastPointCount: int("last_point_count").default(0).notNull(),
		failureStatus: int("failure_status"),
		failureCode: varchar("failure_code", { length: 64 }),
		failureMessage: text("failure_message"),
		failureCount: int("failure_count").default(0).notNull(),
		failedAt: timestamp("failed_at", { fsp: 3 }),
		disabledAt: timestamp("disabled_at", { fsp: 3 }),
		retryAfter: timestamp("retry_after", { fsp: 3 }),
		createdAt: timestamp("created_at", { fsp: 3 }).defaultNow().notNull(),
		updatedAt: timestamp("updated_at", { fsp: 3 })
			.defaultNow()
			.$onUpdate(() => /* @__PURE__ */ new Date())
			.notNull(),
	},
	(table) => [
		index("healthSyncState_userId_idx").on(table.userId),
		index("healthSyncState_disabledAt_lastSyncAt_idx").on(
			table.disabledAt,
			table.lastSyncAt,
		),
	],
);

/** Per-user opt-in switch and the sync's cached view of the user. */
export const healthSyncAccount = mysqlTable("health_sync_account", {
	userId: varchar("user_id", { length: 36 })
		.primaryKey()
		.references(() => user.id, { onDelete: "cascade" }),
	enabled: boolean("enabled").default(false).notNull(),
	enabledAt: timestamp("enabled_at", { fsp: 3 }),
	disabledAt: timestamp("disabled_at", { fsp: 3 }),
	timeZone: varchar("time_zone", { length: 64 }),
	timeZoneSource: varchar("time_zone_source", { length: 16 }),
	membershipStartDateMs: bigint("membership_start_date_ms", {
		mode: "number",
	}),
	lastProbedAt: timestamp("last_probed_at", { fsp: 3 }),
	createdAt: timestamp("created_at", { fsp: 3 }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { fsp: 3 })
		.defaultNow()
		.$onUpdate(() => /* @__PURE__ */ new Date())
		.notNull(),
});

/** The single row that serialises sync invocations. See `./sqlite.ts`. */
export const healthSyncLease = mysqlTable("health_sync_lease", {
	id: varchar("id", { length: 32 }).primaryKey(),
	holder: varchar("holder", { length: 32 }),
	acquiredAt: timestamp("acquired_at", { fsp: 3 }),
	expiresAt: timestamp("expires_at", { fsp: 3 }),
	heartbeatAt: timestamp("heartbeat_at", { fsp: 3 }),
	cursorUserId: varchar("cursor_user_id", { length: 36 }),
	updatedAt: timestamp("updated_at", { fsp: 3 }).defaultNow().notNull(),
});

/** What each sync invocation did. See `./sqlite.ts`. */
export const healthSyncRun = mysqlTable(
	"health_sync_run",
	{
		id: varchar("id", { length: 32 }).primaryKey(),
		startedAt: timestamp("started_at", { fsp: 3 }).notNull(),
		finishedAt: timestamp("finished_at", { fsp: 3 }),
		trigger: varchar("trigger", { length: 16 }).notNull(),
		outcome: varchar("outcome", { length: 32 }),
		usersConsidered: int("users_considered").default(0).notNull(),
		usersTouched: int("users_touched").default(0).notNull(),
		tasksPlanned: int("tasks_planned").default(0).notNull(),
		tasksRan: int("tasks_ran").default(0).notNull(),
		pointsInserted: int("points_inserted").default(0).notNull(),
		pointsUpdated: int("points_updated").default(0).notNull(),
		retries: int("retries").default(0).notNull(),
		blocksWritten: int("blocks_written").default(0).notNull(),
		moreWork: boolean("more_work").default(false).notNull(),
		error: text("error"),
	},
	(table) => [index("healthSyncRun_startedAt_idx").on(table.startedAt)],
);
