import {
	bigint,
	boolean,
	index,
	int,
	json,
	mysqlTable,
	text,
	timestamp,
	varchar,
} from "drizzle-orm/mysql-core";

/**
 * better-auth core tables for MySQL.
 *
 * GENERATED by `pnpm auth:generate:mysql`; regenerate after changing the
 * better-auth config (new plugins, `additionalFields`, ...). The generation
 * command restores this header and removes the legacy `relations()` blocks
 * that drizzle-orm 1.x no longer supports. Application tables belong in
 * `./mysql.ts`, which is not overwritten.
 *
 * Two MySQL-specific details come from the generator and matter: identifiers are
 * `varchar(36)` rather than `text`, because MySQL cannot index an unbounded
 * `TEXT` as a primary or foreign key; and every timestamp carries `fsp: 3` so
 * millisecond precision survives — without it MySQL truncates to whole seconds
 * and session expiry comparisons drift.
 *
 * Table and column names are what the drizzle adapter looks up by convention,
 * so rename nothing here without mirroring it in `src/lib/auth.server.ts`.
 */

export const user = mysqlTable("user", {
	id: varchar("id", { length: 36 }).primaryKey(),
	name: varchar("name", { length: 255 }).notNull(),
	email: varchar("email", { length: 255 }).notNull().unique(),
	emailVerified: boolean("email_verified").default(false).notNull(),
	image: text("image"),
	createdAt: timestamp("created_at", { fsp: 3 }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { fsp: 3 })
		.defaultNow()
		.$onUpdate(() => /* @__PURE__ */ new Date())
		.notNull(),
});

export const session = mysqlTable(
	"session",
	{
		id: varchar("id", { length: 36 }).primaryKey(),
		expiresAt: timestamp("expires_at", { fsp: 3 }).notNull(),
		token: varchar("token", { length: 255 }).notNull().unique(),
		createdAt: timestamp("created_at", { fsp: 3 }).defaultNow().notNull(),
		updatedAt: timestamp("updated_at", { fsp: 3 })
			.$onUpdate(() => /* @__PURE__ */ new Date())
			.notNull(),
		ipAddress: text("ip_address"),
		userAgent: text("user_agent"),
		userId: varchar("user_id", { length: 36 })
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
	},
	(table) => [index("session_userId_idx").on(table.userId)],
);

export const account = mysqlTable(
	"account",
	{
		id: varchar("id", { length: 36 }).primaryKey(),
		accountId: text("account_id").notNull(),
		providerId: text("provider_id").notNull(),
		userId: varchar("user_id", { length: 36 })
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
		accessToken: text("access_token"),
		refreshToken: text("refresh_token"),
		idToken: text("id_token"),
		accessTokenExpiresAt: timestamp("access_token_expires_at", { fsp: 3 }),
		refreshTokenExpiresAt: timestamp("refresh_token_expires_at", { fsp: 3 }),
		scope: text("scope"),
		password: text("password"),
		createdAt: timestamp("created_at", { fsp: 3 }).defaultNow().notNull(),
		updatedAt: timestamp("updated_at", { fsp: 3 })
			.$onUpdate(() => /* @__PURE__ */ new Date())
			.notNull(),
	},
	(table) => [index("account_userId_idx").on(table.userId)],
);

export const verification = mysqlTable(
	"verification",
	{
		id: varchar("id", { length: 36 }).primaryKey(),
		identifier: varchar("identifier", { length: 255 }).notNull(),
		value: text("value").notNull(),
		expiresAt: timestamp("expires_at", { fsp: 3 }).notNull(),
		createdAt: timestamp("created_at", { fsp: 3 }).defaultNow().notNull(),
		updatedAt: timestamp("updated_at", { fsp: 3 })
			.defaultNow()
			.$onUpdate(() => /* @__PURE__ */ new Date())
			.notNull(),
	},
	(table) => [index("verification_identifier_idx").on(table.identifier)],
);

export const apikey = mysqlTable(
	"apikey",
	{
		id: varchar("id", { length: 36 }).primaryKey(),
		configId: varchar("config_id", { length: 255 })
			.default("default")
			.notNull(),
		name: text("name"),
		start: text("start"),
		referenceId: varchar("reference_id", { length: 255 }).notNull(),
		prefix: text("prefix"),
		key: varchar("key", { length: 255 }).notNull(),
		refillInterval: int("refill_interval"),
		refillAmount: int("refill_amount"),
		lastRefillAt: timestamp("last_refill_at", { fsp: 3 }),
		enabled: boolean("enabled").default(true),
		rateLimitEnabled: boolean("rate_limit_enabled").default(true),
		rateLimitTimeWindow: int("rate_limit_time_window").default(1000),
		rateLimitMax: int("rate_limit_max").default(10000),
		requestCount: int("request_count").default(0),
		remaining: int("remaining"),
		lastRequest: timestamp("last_request", { fsp: 3 }),
		expiresAt: timestamp("expires_at", { fsp: 3 }),
		createdAt: timestamp("created_at", { fsp: 3 }).notNull(),
		updatedAt: timestamp("updated_at", { fsp: 3 }).notNull(),
		permissions: text("permissions"),
		metadata: text("metadata"),
	},
	(table) => [
		index("apikey_configId_idx").on(table.configId),
		index("apikey_referenceId_idx").on(table.referenceId),
		index("apikey_key_idx").on(table.key),
	],
);

export const jwks = mysqlTable("jwks", {
	id: varchar("id", { length: 36 }).primaryKey(),
	publicKey: text("public_key").notNull(),
	privateKey: text("private_key").notNull(),
	createdAt: timestamp("created_at", { fsp: 3 }).notNull(),
	expiresAt: timestamp("expires_at", { fsp: 3 }),
});

export const oauthClient = mysqlTable(
	"oauth_client",
	{
		id: varchar("id", { length: 36 }).primaryKey(),
		clientId: varchar("client_id", { length: 255 }).notNull().unique(),
		clientSecret: text("client_secret"),
		disabled: boolean("disabled").default(false),
		skipConsent: boolean("skip_consent"),
		enableEndSession: boolean("enable_end_session"),
		subjectType: text("subject_type"),
		scopes: text("scopes"),
		userId: varchar("user_id", { length: 36 }).references(() => user.id, {
			onDelete: "cascade",
		}),
		createdAt: timestamp("created_at", { fsp: 3 }),
		updatedAt: timestamp("updated_at", { fsp: 3 }),
		name: text("name"),
		uri: text("uri"),
		icon: text("icon"),
		contacts: text("contacts"),
		tos: text("tos"),
		policy: text("policy"),
		softwareId: text("software_id"),
		softwareVersion: text("software_version"),
		softwareStatement: text("software_statement"),
		redirectUris: text("redirect_uris").notNull(),
		postLogoutRedirectUris: text("post_logout_redirect_uris"),
		tokenEndpointAuthMethod: text("token_endpoint_auth_method"),
		grantTypes: text("grant_types"),
		responseTypes: text("response_types"),
		public: boolean("public"),
		type: text("type"),
		requirePKCE: boolean("require_pkce"),
		referenceId: text("reference_id"),
		metadata: json("metadata"),
	},
	(table) => [index("oauthClient_userId_idx").on(table.userId)],
);

export const oauthRefreshToken = mysqlTable(
	"oauth_refresh_token",
	{
		id: varchar("id", { length: 36 }).primaryKey(),
		token: varchar("token", { length: 255 }).notNull().unique(),
		clientId: varchar("client_id", { length: 255 })
			.notNull()
			.references(() => oauthClient.clientId, { onDelete: "cascade" }),
		sessionId: varchar("session_id", { length: 36 }).references(
			() => session.id,
			{ onDelete: "set null" },
		),
		userId: varchar("user_id", { length: 36 })
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
		referenceId: text("reference_id"),
		expiresAt: timestamp("expires_at", { fsp: 3 }).notNull(),
		createdAt: timestamp("created_at", { fsp: 3 }).notNull(),
		revoked: timestamp("revoked", { fsp: 3 }),
		authTime: timestamp("auth_time", { fsp: 3 }),
		scopes: text("scopes").notNull(),
	},
	(table) => [
		index("oauthRefreshToken_clientId_idx").on(table.clientId),
		index("oauthRefreshToken_sessionId_idx").on(table.sessionId),
		index("oauthRefreshToken_userId_idx").on(table.userId),
	],
);

export const oauthAccessToken = mysqlTable(
	"oauth_access_token",
	{
		id: varchar("id", { length: 36 }).primaryKey(),
		token: varchar("token", { length: 255 }).notNull().unique(),
		clientId: varchar("client_id", { length: 255 })
			.notNull()
			.references(() => oauthClient.clientId, { onDelete: "cascade" }),
		sessionId: varchar("session_id", { length: 36 }).references(
			() => session.id,
			{ onDelete: "set null" },
		),
		userId: varchar("user_id", { length: 36 }).references(() => user.id, {
			onDelete: "cascade",
		}),
		referenceId: text("reference_id"),
		refreshId: varchar("refresh_id", { length: 36 }).references(
			() => oauthRefreshToken.id,
			{ onDelete: "cascade" },
		),
		expiresAt: timestamp("expires_at", { fsp: 3 }).notNull(),
		createdAt: timestamp("created_at", { fsp: 3 }).notNull(),
		scopes: text("scopes").notNull(),
	},
	(table) => [
		index("oauthAccessToken_clientId_idx").on(table.clientId),
		index("oauthAccessToken_sessionId_idx").on(table.sessionId),
		index("oauthAccessToken_userId_idx").on(table.userId),
		index("oauthAccessToken_refreshId_idx").on(table.refreshId),
	],
);

export const oauthConsent = mysqlTable(
	"oauth_consent",
	{
		id: varchar("id", { length: 36 }).primaryKey(),
		clientId: varchar("client_id", { length: 255 })
			.notNull()
			.references(() => oauthClient.clientId, { onDelete: "cascade" }),
		userId: varchar("user_id", { length: 36 }).references(() => user.id, {
			onDelete: "cascade",
		}),
		referenceId: text("reference_id"),
		scopes: text("scopes").notNull(),
		createdAt: timestamp("created_at", { fsp: 3 }).notNull(),
		updatedAt: timestamp("updated_at", { fsp: 3 }).notNull(),
	},
	(table) => [
		index("oauthConsent_clientId_idx").on(table.clientId),
		index("oauthConsent_userId_idx").on(table.userId),
	],
);

export const rateLimit = mysqlTable("rate_limit", {
	id: varchar("id", { length: 36 }).primaryKey(),
	key: varchar("key", { length: 255 }).notNull().unique(),
	count: int("count").notNull(),
	lastRequest: bigint("last_request", { mode: "number" }).notNull(),
});
