import {
	boolean,
	index,
	int,
	mysqlTable,
	text,
	timestamp,
	varchar,
} from "drizzle-orm/mysql-core";

/**
 * better-auth core tables for MySQL.
 *
 * GENERATED by `pnpm auth:generate:mysql`; regenerate after changing the
 * better-auth config (new plugins, `additionalFields`, ...). Two edits survive
 * by hand each time: this comment, and the deletion of the legacy `relations()`
 * blocks the generator still emits — drizzle-orm 1.x replaced them with
 * `defineRelations` and the adapter needs neither. Application tables belong in
 * `./mysql.ts`, which is not overwritten.
 *
 * Two MySQL-specific details come from the generator and matter: identifiers are
 * `varchar(36)` rather than `text`, because MySQL cannot index an unbounded
 * `TEXT` as a primary or foreign key; and every timestamp carries `fsp: 3` so
 * millisecond precision survives — without it MySQL truncates to whole seconds
 * and session expiry comparisons drift.
 *
 * Table and column names are what the drizzle adapter looks up by convention,
 * so rename nothing here without mirroring it in `src/lib/auth.server.ts`.
 */

export const user = mysqlTable("user", {
	id: varchar("id", { length: 36 }).primaryKey(),
	name: varchar("name", { length: 255 }).notNull(),
	email: varchar("email", { length: 255 }).notNull().unique(),
	emailVerified: boolean("email_verified").default(false).notNull(),
	image: text("image"),
	createdAt: timestamp("created_at", { fsp: 3 }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { fsp: 3 })
		.defaultNow()
		.$onUpdate(() => /* @__PURE__ */ new Date())
		.notNull(),
});

export const session = mysqlTable(
	"session",
	{
		id: varchar("id", { length: 36 }).primaryKey(),
		expiresAt: timestamp("expires_at", { fsp: 3 }).notNull(),
		token: varchar("token", { length: 255 }).notNull().unique(),
		createdAt: timestamp("created_at", { fsp: 3 }).defaultNow().notNull(),
		updatedAt: timestamp("updated_at", { fsp: 3 })
			.$onUpdate(() => /* @__PURE__ */ new Date())
			.notNull(),
		ipAddress: text("ip_address"),
		userAgent: text("user_agent"),
		userId: varchar("user_id", { length: 36 })
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
	},
	(table) => [index("session_userId_idx").on(table.userId)],
);

export const account = mysqlTable(
	"account",
	{
		id: varchar("id", { length: 36 }).primaryKey(),
		accountId: text("account_id").notNull(),
		providerId: text("provider_id").notNull(),
		userId: varchar("user_id", { length: 36 })
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
		accessToken: text("access_token"),
		refreshToken: text("refresh_token"),
		idToken: text("id_token"),
		accessTokenExpiresAt: timestamp("access_token_expires_at", { fsp: 3 }),
		refreshTokenExpiresAt: timestamp("refresh_token_expires_at", { fsp: 3 }),
		scope: text("scope"),
		password: text("password"),
		createdAt: timestamp("created_at", { fsp: 3 }).defaultNow().notNull(),
		updatedAt: timestamp("updated_at", { fsp: 3 })
			.$onUpdate(() => /* @__PURE__ */ new Date())
			.notNull(),
	},
	(table) => [index("account_userId_idx").on(table.userId)],
);

export const verification = mysqlTable(
	"verification",
	{
		id: varchar("id", { length: 36 }).primaryKey(),
		identifier: varchar("identifier", { length: 255 }).notNull(),
		value: text("value").notNull(),
		expiresAt: timestamp("expires_at", { fsp: 3 }).notNull(),
		createdAt: timestamp("created_at", { fsp: 3 }).defaultNow().notNull(),
		updatedAt: timestamp("updated_at", { fsp: 3 })
			.defaultNow()
			.$onUpdate(() => /* @__PURE__ */ new Date())
			.notNull(),
	},
	(table) => [index("verification_identifier_idx").on(table.identifier)],
);

export const apikey = mysqlTable(
	"apikey",
	{
		id: varchar("id", { length: 36 }).primaryKey(),
		configId: varchar("config_id", { length: 255 })
			.default("default")
			.notNull(),
		name: text("name"),
		start: text("start"),
		referenceId: varchar("reference_id", { length: 255 }).notNull(),
		prefix: text("prefix"),
		key: varchar("key", { length: 255 }).notNull(),
		refillInterval: int("refill_interval"),
		refillAmount: int("refill_amount"),
		lastRefillAt: timestamp("last_refill_at", { fsp: 3 }),
		enabled: boolean("enabled").default(true),
		rateLimitEnabled: boolean("rate_limit_enabled").default(true),
		rateLimitTimeWindow: int("rate_limit_time_window").default(1000),
		rateLimitMax: int("rate_limit_max").default(100),
		requestCount: int("request_count").default(0),
		remaining: int("remaining"),
		lastRequest: timestamp("last_request", { fsp: 3 }),
		expiresAt: timestamp("expires_at", { fsp: 3 }),
		createdAt: timestamp("created_at", { fsp: 3 }).notNull(),
		updatedAt: timestamp("updated_at", { fsp: 3 }).notNull(),
		permissions: text("permissions"),
		metadata: text("metadata"),
	},
	(table) => [
		index("apikey_configId_idx").on(table.configId),
		index("apikey_referenceId_idx").on(table.referenceId),
		index("apikey_key_idx").on(table.key),
	],
);
