/**
 * MySQL schema.
 *
 * `./mysql-auth.ts` is generated by better-auth's schema generator. It is
 * re-exported here so `drizzle-kit generate` picks it up. Any application table
 * added later moves as a set with `./sqlite.ts` and `./postgresql.ts`, and must
 * avoid the MySQL traps `scripts/normalize-auth-schema.ts` strips out of
 * generated output.
 */
export * from "./mysql-auth";
