/**
 * PostgreSQL schema.
 *
 * `./postgresql-auth.ts` is generated by better-auth's schema generator. It is
 * re-exported here so `drizzle-kit generate` picks it up. Any application table
 * added later moves as a set with `./sqlite.ts` and `./mysql.ts`.
 */
export * from "./postgresql-auth";
