import {
	bigint,
	boolean,
	index,
	integer,
	jsonb,
	pgTable,
	text,
	timestamp,
} from "drizzle-orm/pg-core";
import { user } from "./postgresql-auth";

/**
 * PostgreSQL schema.
 *
 * `./postgresql-auth.ts` is generated by better-auth's schema generator.
 *
 * The application tables below are the health data cache. They exist in all
 * three dialect modules under the same table and column *names*; only the types
 * differ. They move as a set — editing one alone is what produces an app that
 * works on SQLite and falls over on Postgres. `./sqlite.ts` carries the
 * commentary explaining each decision.
 */
export * from "./postgresql-auth";

/** Cached Google Health data points. See `./sqlite.ts` for the rationale. */
export const healthDataPoint = pgTable(
	"health_data_point",
	{
		id: text("id").primaryKey(),
		userId: text("user_id")
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
		dataType: text("data_type").notNull(),
		grain: text("grain").default("point").notNull(),
		timeShape: text("time_shape").notNull(),
		observedAtMs: bigint("observed_at_ms", { mode: "number" }).notNull(),
		observedEndMs: bigint("observed_end_ms", { mode: "number" }).notNull(),
		observedTime: jsonb("observed_time")
			.$type<Record<string, unknown>>()
			.notNull(),
		value: jsonb("value").$type<Record<string, unknown>>().notNull(),
		source: jsonb("source").$type<Record<string, unknown>>(),
		sourceKey: text("source_key"),
		resourceName: text("resource_name"),
		contentHash: text("content_hash").notNull(),
		syncedAt: timestamp("synced_at").notNull(),
		createdAt: timestamp("created_at").defaultNow().notNull(),
	},
	(table) => [
		index("healthDataPoint_userId_dataType_observedAtMs_idx").on(
			table.userId,
			table.dataType,
			table.observedAtMs,
		),
	],
);

/** Per (user, data type) sync watermarks and failure state. */
export const healthSyncState = pgTable(
	"health_sync_state",
	{
		id: text("id").primaryKey(),
		userId: text("user_id")
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
		dataType: text("data_type").notNull(),
		coveredFromMs: bigint("covered_from_ms", { mode: "number" }),
		coveredThroughMs: bigint("covered_through_ms", { mode: "number" }),
		backfillComplete: boolean("backfill_complete").default(false).notNull(),
		lastSyncAt: timestamp("last_sync_at"),
		lastAttemptAt: timestamp("last_attempt_at"),
		lastPointCount: integer("last_point_count").default(0).notNull(),
		failureStatus: integer("failure_status"),
		failureCode: text("failure_code"),
		failureMessage: text("failure_message"),
		failureCount: integer("failure_count").default(0).notNull(),
		failedAt: timestamp("failed_at"),
		disabledAt: timestamp("disabled_at"),
		retryAfter: timestamp("retry_after"),
		createdAt: timestamp("created_at").defaultNow().notNull(),
		updatedAt: timestamp("updated_at")
			.defaultNow()
			.$onUpdate(() => /* @__PURE__ */ new Date())
			.notNull(),
	},
	(table) => [
		index("healthSyncState_userId_idx").on(table.userId),
		index("healthSyncState_disabledAt_lastSyncAt_idx").on(
			table.disabledAt,
			table.lastSyncAt,
		),
	],
);

/** Per-user opt-in switch and the sync's cached view of the user. */
export const healthSyncAccount = pgTable("health_sync_account", {
	userId: text("user_id")
		.primaryKey()
		.references(() => user.id, { onDelete: "cascade" }),
	enabled: boolean("enabled").default(false).notNull(),
	enabledAt: timestamp("enabled_at"),
	disabledAt: timestamp("disabled_at"),
	timeZone: text("time_zone"),
	timeZoneSource: text("time_zone_source"),
	membershipStartDateMs: bigint("membership_start_date_ms", {
		mode: "number",
	}),
	lastProbedAt: timestamp("last_probed_at"),
	createdAt: timestamp("created_at").defaultNow().notNull(),
	updatedAt: timestamp("updated_at")
		.defaultNow()
		.$onUpdate(() => /* @__PURE__ */ new Date())
		.notNull(),
});

/** The single row that serialises sync invocations. See `./sqlite.ts`. */
export const healthSyncLease = pgTable("health_sync_lease", {
	id: text("id").primaryKey(),
	holder: text("holder"),
	acquiredAt: timestamp("acquired_at"),
	expiresAt: timestamp("expires_at"),
	heartbeatAt: timestamp("heartbeat_at"),
	cursorUserId: text("cursor_user_id"),
	updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

/** What each sync invocation did. See `./sqlite.ts`. */
export const healthSyncRun = pgTable(
	"health_sync_run",
	{
		id: text("id").primaryKey(),
		startedAt: timestamp("started_at").notNull(),
		finishedAt: timestamp("finished_at"),
		trigger: text("trigger").notNull(),
		outcome: text("outcome"),
		usersConsidered: integer("users_considered").default(0).notNull(),
		usersTouched: integer("users_touched").default(0).notNull(),
		tasksPlanned: integer("tasks_planned").default(0).notNull(),
		tasksRan: integer("tasks_ran").default(0).notNull(),
		pointsInserted: integer("points_inserted").default(0).notNull(),
		pointsUpdated: integer("points_updated").default(0).notNull(),
		retries: integer("retries").default(0).notNull(),
		blocksWritten: integer("blocks_written").default(0).notNull(),
		moreWork: boolean("more_work").default(false).notNull(),
		error: text("error"),
	},
	(table) => [index("healthSyncRun_startedAt_idx").on(table.startedAt)],
);
