import { readFile, writeFile } from "node:fs/promises";

/**
 * Normalizes better-auth CLI output for this repository.
 *
 * The generator overwrites the explanatory header and emits legacy
 * `relations()` helpers from drizzle-orm 0.x. drizzle-orm 1.x removed that API,
 * so one generated dialect would otherwise make the next dialect fail while it
 * imports the shared schema index. It also emits SQLite's `{ mode: "json" }`
 * option on MySQL `text()` and `json()` columns, where drizzle-orm rejects it,
 * and narrows OAuth `client_id` references to `varchar(36)` even though their
 * unique parent column is `varchar(255)`. Keep this post-processing beside the
 * generation command so all three dialects always receive the same treatment.
 */

const DIALECT_CONFIG = {
	sqlite: {
		path: "src/db/schema/sqlite-auth.ts",
		header: `/**
 * better-auth core tables for SQLite — used by both Turso (\`libsql://\`) and a
 * local \`file:\` database.
 *
 * GENERATED by \`pnpm auth:generate:sqlite\`; regenerate after changing the
 * better-auth config (new plugins, \`additionalFields\`, ...). The generation
 * command restores this header and removes the legacy \`relations()\` blocks
 * that drizzle-orm 1.x no longer supports. Application tables belong in
 * \`./sqlite.ts\`, which is not overwritten.
 *
 * Table and column names are what the drizzle adapter looks up by convention,
 * so rename nothing here without mirroring it in \`src/lib/auth.server.ts\`.
 */`,
	},
	postgresql: {
		path: "src/db/schema/postgresql-auth.ts",
		header: `/**
 * better-auth core tables for PostgreSQL.
 *
 * GENERATED by \`pnpm auth:generate:postgresql\`; regenerate after changing the
 * better-auth config (new plugins, \`additionalFields\`, ...). The generation
 * command restores this header and removes the legacy \`relations()\` blocks
 * that drizzle-orm 1.x no longer supports. Application tables belong in
 * \`./postgresql.ts\`, which is not overwritten.
 *
 * Table and column names are what the drizzle adapter looks up by convention,
 * so rename nothing here without mirroring it in \`src/lib/auth.server.ts\`.
 */`,
	},
	mysql: {
		path: "src/db/schema/mysql-auth.ts",
		header: `/**
 * better-auth core tables for MySQL.
 *
 * GENERATED by \`pnpm auth:generate:mysql\`; regenerate after changing the
 * better-auth config (new plugins, \`additionalFields\`, ...). The generation
 * command restores this header and removes the legacy \`relations()\` blocks
 * that drizzle-orm 1.x no longer supports. Application tables belong in
 * \`./mysql.ts\`, which is not overwritten.
 *
 * Two MySQL-specific details come from the generator and matter: identifiers are
 * \`varchar(36)\` rather than \`text\`, because MySQL cannot index an unbounded
 * \`TEXT\` as a primary or foreign key; and every timestamp carries \`fsp: 3\` so
 * millisecond precision survives — without it MySQL truncates to whole seconds
 * and session expiry comparisons drift.
 *
 * Table and column names are what the drizzle adapter looks up by convention,
 * so rename nothing here without mirroring it in \`src/lib/auth.server.ts\`.
 */`,
	},
} as const;

type Dialect = keyof typeof DIALECT_CONFIG;

const DRIZZLE_IMPORT = /^import \{ ([^}]+) \} from "drizzle-orm";\n?/m;
const RELATIONS_START = /\nexport const \w+Relations = relations\(/;
const MYSQL_UNSUPPORTED_JSON_MODE =
	/\b(text|json)\(([^,\n]+), \{ mode: "json" \}\)/g;
const MYSQL_NARROW_OAUTH_CLIENT_ID =
	/clientId: varchar\("client_id", \{ length: 36 \}\)/g;

function isDialect(value: string | undefined): value is Dialect {
	return value !== undefined && value in DIALECT_CONFIG;
}

function removeRelationsImport(source: string): string {
	return source.replace(DRIZZLE_IMPORT, (_statement, names: string) => {
		const kept = names
			.split(",")
			.map((name) => name.trim())
			.filter((name) => name !== "relations");
		return kept.length > 0
			? `import { ${kept.join(", ")} } from "drizzle-orm";\n`
			: "";
	});
}

function normalize(source: string, header: string, dialect: Dialect): string {
	const relationStart = source.search(RELATIONS_START);
	if (relationStart < 0) {
		throw new Error("Generated schema did not contain legacy relations blocks");
	}

	const tablesOnly = removeRelationsImport(
		source.slice(0, relationStart),
	).trimEnd();
	const firstTable = tablesOnly.indexOf("export const ");
	if (firstTable < 0) {
		throw new Error("Generated schema did not contain any exported tables");
	}

	const imports = tablesOnly.slice(0, firstTable).trimEnd();
	const rawTables = tablesOnly.slice(firstTable);
	const tables =
		dialect === "mysql"
			? rawTables
					.replace(MYSQL_UNSUPPORTED_JSON_MODE, "$1($2)")
					.replace(
						MYSQL_NARROW_OAUTH_CLIENT_ID,
						'clientId: varchar("client_id", { length: 255 })',
					)
			: rawTables;
	const output = `${imports}\n\n${header}\n\n${tables}\n`;
	if (RELATIONS_START.test(output)) {
		throw new Error("Legacy relations blocks remain after normalization");
	}
	return output;
}

async function main(): Promise<void> {
	const dialect = process.argv.at(2);
	if (!isDialect(dialect)) {
		throw new Error("Expected one dialect: sqlite, postgresql, or mysql");
	}

	const config = DIALECT_CONFIG[dialect];
	const source = await readFile(config.path, "utf8");
	await writeFile(
		config.path,
		normalize(source, config.header, dialect),
		"utf8",
	);
	process.stdout.write(
		`${JSON.stringify({ event: "auth_schema_normalized", dialect, path: config.path })}\n`,
	);
}

main().catch((error: unknown) => {
	process.stderr.write(
		`${JSON.stringify({
			event: "auth_schema_normalization_failed",
			error: error instanceof Error ? error.message : String(error),
		})}\n`,
	);
	process.exitCode = 1;
});
